stages:
  - build
  - publish


.template/build/manylinux: &template-build-manylinux
  stage: build
  image: quay.io/pypa/manylinux2014_x86_64

  script:
    - yum install -y capnproto
    - ${PYBIN}/pip install poetry-core setuptools capnpy
    - ${PYBIN}/pip wheel . --no-deps --no-build-isolation -w dist
    - auditwheel repair --wheel-dir dist/ dist/*.whl
    - rm dist/*manylinux_2_17_x86_64.whl
  artifacts:
    paths:
      - dist

build/manylinux/3.9:
  <<: *template-build-manylinux
  variables:
    PYBIN: /opt/python/cp39-cp39/bin

build/manylinux/3.10:
  <<: *template-build-manylinux
  variables:
    PYBIN: /opt/python/cp310-cp310/bin

build/manylinux/3.11:
  <<: *template-build-manylinux
  variables:
    PYBIN: /opt/python/cp311-cp311/bin


build/manylinux/arm64:
  stage: build
  image:
    name: quay.io/podman/stable
  script:
    - |
      podman run --rm --override-arch arm64 -t -v .:/io quay.io/pypa/manylinux2014_aarch64 sh -c "yum install -y epel-release;
        yum install -y capnproto;
        /opt/python/cp39-cp39/bin/pip install poetry-core setuptools capnpy;
        /opt/python/cp311-cp311/bin/pip install poetry-core setuptools capnpy;
        /opt/python/cp310-cp310/bin/pip install poetry-core setuptools capnpy;
        cd /io;
        /opt/python/cp39-cp39/bin/pip wheel . --no-deps --no-build-isolation -w dist;
        sh ./pre-build.sh;
        /opt/python/cp310-cp310/bin/pip wheel . --no-deps --no-build-isolation -w dist;
        sh ./pre-build.sh;
        /opt/python/cp311-cp311/bin/pip wheel . --no-deps --no-build-isolation -w dist;
        auditwheel repair --wheel-dir dist/ dist/*.whl;
        rm dist/*manylinux_2_17_aarch64.whl"
  artifacts:
    paths:
      - dist

build/manylinux/pypy:
  stage: build
  image: quay.io/pypa/manylinux2014_x86_64

  script:
    - yum install -y capnproto
    - ${PYBIN}/pip install poetry-core setuptools capnpy
    - ${PYBIN}/pip wheel . --no-deps --no-build-isolation -w dist
    - old=$(ls -1 dist/*pp310-pypy310_pp73*.whl)
    - new=$(echo $old | sed -e 's/pp310-pypy310_pp73-manylinux_2_17_x86_64/py3-none-any/')
    - mv -v "$old" "$new"
  artifacts:
    paths:
      - dist
  variables:
    PYBIN: /opt/python/pp310-pypy310_pp73/bin

build/sdist:
  stage: build
  image: quay.io/pypa/manylinux2014_x86_64
  script:
    - ${PYBIN}/python -m pip install --upgrade pip
    - ${PYBIN}/pip install poetry
    - ${PYBIN}/poetry build --format sdist
  artifacts:
    paths:
      - dist
  variables:
    PYBIN: /opt/python/cp311-cp311/bin

list_wheels:
  stage: publish
  image: quay.io/pypa/manylinux2014_x86_64
  script:
    - ${PYBIN}/python -m pip install --upgrade pip
    - ${PYBIN}/pip install twine
    - twine upload dist/*.whl
    - twine upload dist/*.tar.gz
  variables:
    PYBIN: /opt/python/cp311-cp311/bin
    TWINE_USERNAME: ${PYPI_USERNAME}
    TWINE_PASSWORD: ${PYPI_TOKEN}